version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:5000"  # Use port 8080 externally to avoid conflicts
    environment:
      - NODE_ENV=production
      - IS_DOCKER=true
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - mysafety-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: mysafety
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysafety123
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mysafety-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  mysafety-network:
    driver: bridge