version: '3.8'

services:
  # PostgreSQL Database for development
  postgres-dev:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=safety_dev_db
    ports:
      - "5437:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - mysafety-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MySafety Application for development
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=5000
      - IS_DOCKER=true
      - DATABASE_URL=postgres://postgres:postgres@postgres-dev:5432/safety_dev_db
      - SESSION_SECRET=dev-session-secret-key
    ports:
      - "5006:5000"  # Different external port to avoid conflicts
    volumes:
      - ./uploads:/app/uploads
      - .:/app  # Mount source code for development
    networks:
      - mysafety-dev-network
    depends_on:
      postgres-dev:
        condition: service_healthy
    command: ["sh", "-c", "npm install && npx drizzle-kit generate && npx drizzle-kit push --config=drizzle.config.ts && npm run dev"]  # Install, generate migrations, push schema, and run

volumes:
  postgres_dev_data:

networks:
  mysafety-dev-network:
    driver: bridge