-- SQL to insert mock incidents
BEGIN;
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    2, 
    'Struck By incident at Downtown Project', 
    'Worker fell from ladder while changing a light fixture. Ladder appeared to be properly set up but may have shifted during use.', 
    '2025-04-02T22:59:16.825Z', 
    'Parking structure, level 2', 
    'Struck By', 
    'critical', 
    'resolved', 
    true, 
    'Worker received minor injury requiring first aid.',
    'Investigation determined that the incident was caused by environmental factors',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Regular safety training scheduled',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    1, 
    'Caught In/Between incident at Main Construction Site', 
    'Vehicle backed into scaffold structure causing partial collapse. No injuries but equipment damage occurred.', 
    '2025-05-10T03:15:01.496Z', 
    'Electrical room', 
    'Caught In/Between', 
    'major', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    4, 
    'Fall incident at Downtown Project', 
    'Heavy equipment operator reported near-miss with pedestrian worker who entered operational zone without authorization.', 
    '2025-03-01T04:35:39.907Z', 
    'Equipment yard', 
    'Fall', 
    'major', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by inadequate training',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Regular safety training scheduled',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    3, 
    'Fall incident at Main Construction Site', 
    'Subcontractor was not wearing proper PPE while operating cutting tool.', 
    '2025-03-18T01:05:46.906Z', 
    'Storage room B', 
    'Fall', 
    'major', 
    'reported', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    2, 
    'Electrical incident at Main Construction Site', 
    'Excavation wall partially collapsed during heavy rain. No workers were in the trench at the time.', 
    '2025-05-19T10:21:18.285Z', 
    'Concrete pouring zone', 
    'Electrical', 
    'moderate', 
    'reported', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    3, 
    3, 
    'Environmental incident at Highway Extension', 
    'Worker received minor cut on hand while using box cutter. First aid was administered on site.', 
    '2025-02-27T11:45:09.864Z', 
    'Scaffolding on north face', 
    'Environmental', 
    'minor', 
    'reported', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    3, 
    2, 
    'Environmental incident at Highway Extension', 
    'Excavation wall partially collapsed during heavy rain. No workers were in the trench at the time.', 
    '2025-03-05T15:25:29.213Z', 
    'Electrical room', 
    'Environmental', 
    'minor', 
    'closed', 
    true, 
    'Worker received minor injury requiring first aid.',
    'Investigation determined that the incident was caused by equipment failure',
    'Actions taken: Environmental controls improved',
    'To prevent recurrence: Daily equipment inspections',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    4, 
    'Equipment Failure incident at Main Construction Site', 
    'Heavy equipment operator reported near-miss with pedestrian worker who entered operational zone without authorization.', 
    '2025-04-15T03:58:10.921Z', 
    'Storage room B', 
    'Equipment Failure', 
    'moderate', 
    'closed', 
    true, 
    'Worker received minor injury requiring first aid.',
    'Investigation determined that the incident was caused by inadequate training',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Regular safety training scheduled',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    1, 
    'Fire/Explosion incident at Downtown Project', 
    'Vehicle backed into scaffold structure causing partial collapse. No injuries but equipment damage occurred.', 
    '2025-04-17T22:31:56.548Z', 
    'Concrete pouring zone', 
    'Fire/Explosion', 
    'critical', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by procedural gap',
    'Actions taken: Environmental controls improved',
    'To prevent recurrence: Improved signage installed',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    3, 
    3, 
    'Fall incident at Highway Extension', 
    'Subcontractor was not wearing proper PPE while operating cutting tool.', 
    '2025-03-22T20:53:38.802Z', 
    'South entrance', 
    'Fall', 
    'moderate', 
    'resolved', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by procedural gap',
    'Actions taken: Equipment replaced',
    'To prevent recurrence: Daily equipment inspections',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    3, 
    'Vehicle Accident incident at Downtown Project', 
    'Excavation wall partially collapsed during heavy rain. No workers were in the trench at the time.', 
    '2025-03-25T03:45:37.036Z', 
    'Main hallway', 
    'Vehicle Accident', 
    'major', 
    'reported', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    3, 
    'Environmental incident at Main Construction Site', 
    'Electrical short in temporary wiring caused small fire. Fire was extinguished with nearby extinguisher. No structural damage.', 
    '2025-04-30T07:46:49.844Z', 
    'Storage room B', 
    'Environmental', 
    'moderate', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by environmental factors',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Regular safety training scheduled',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    1, 
    'Other incident at Downtown Project', 
    'Vehicle backed into scaffold structure causing partial collapse. No injuries but equipment damage occurred.', 
    '2025-03-26T19:48:51.953Z', 
    'Parking structure, level 2', 
    'Other', 
    'minor', 
    'reported', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    1, 
    'Equipment Failure incident at Main Construction Site', 
    'Worker received minor cut on hand while using box cutter. First aid was administered on site.', 
    '2025-03-17T01:49:10.300Z', 
    'Storage room B', 
    'Equipment Failure', 
    'major', 
    'resolved', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by inadequate training',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Improved signage installed',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    2, 
    'Fire/Explosion incident at Main Construction Site', 
    'Chemical spill occurred in storage area. Approximately 2 gallons of paint thinner spilled. Area was contained and cleaned according to protocol.', 
    '2025-02-24T13:54:49.131Z', 
    'West loading dock', 
    'Fire/Explosion', 
    'critical', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by environmental factors',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Regular safety training scheduled',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    4, 
    'Slip/Trip incident at Downtown Project', 
    'Worker fell from ladder while changing a light fixture. Ladder appeared to be properly set up but may have shifted during use.', 
    '2025-03-23T17:48:35.321Z', 
    'Electrical room', 
    'Slip/Trip', 
    'critical', 
    'investigating', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    2, 
    'Security incident at Downtown Project', 
    'Chemical spill occurred in storage area. Approximately 2 gallons of paint thinner spilled. Area was contained and cleaned according to protocol.', 
    '2025-05-21T23:58:38.014Z', 
    'Concrete pouring zone', 
    'Security', 
    'moderate', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by equipment failure',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Regular safety training scheduled',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    3, 
    'Fall incident at Main Construction Site', 
    'Worker received minor cut on hand while using box cutter. First aid was administered on site.', 
    '2025-05-12T15:07:20.154Z', 
    'Elevator shaft', 
    'Fall', 
    'minor', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    1, 
    'Security incident at Downtown Project', 
    'Heavy equipment operator reported near-miss with pedestrian worker who entered operational zone without authorization.', 
    '2025-03-23T15:28:54.612Z', 
    'Equipment yard', 
    'Security', 
    'minor', 
    'reported', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    4, 
    'Fall incident at Downtown Project', 
    'Water pipe burst causing flooding in basement level. Electrical equipment was exposed to water.', 
    '2025-04-18T22:15:01.755Z', 
    'Parking structure, level 2', 
    'Fall', 
    'critical', 
    'reported', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    3, 
    4, 
    'Caught In/Between incident at Highway Extension', 
    'Chemical spill occurred in storage area. Approximately 2 gallons of paint thinner spilled. Area was contained and cleaned according to protocol.', 
    '2025-02-24T19:52:30.582Z', 
    'West loading dock', 
    'Caught In/Between', 
    'critical', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by equipment failure',
    'Actions taken: Environmental controls improved',
    'To prevent recurrence: Enhanced monitoring process',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    4, 
    'Security incident at Main Construction Site', 
    'Subcontractor was not wearing proper PPE while operating cutting tool.', 
    '2025-04-30T17:13:13.575Z', 
    'Storage room B', 
    'Security', 
    'major', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    1, 
    'Fall incident at Downtown Project', 
    'Subcontractor was not wearing proper PPE while operating cutting tool.', 
    '2025-03-04T07:39:12.884Z', 
    'Equipment yard', 
    'Fall', 
    'minor', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    4, 
    'Equipment Failure incident at Downtown Project', 
    'Worker fell from ladder while changing a light fixture. Ladder appeared to be properly set up but may have shifted during use.', 
    '2025-04-11T22:44:24.394Z', 
    'Basement level', 
    'Equipment Failure', 
    'critical', 
    'investigating', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    2, 
    4, 
    'Equipment Failure incident at Downtown Project', 
    'Excavation wall partially collapsed during heavy rain. No workers were in the trench at the time.', 
    '2025-02-23T13:55:15.998Z', 
    'Storage room B', 
    'Equipment Failure', 
    'major', 
    'reported', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
COMMIT;
