-- SQL to insert mock incidents
BEGIN;
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    13, 
    'Struck By incident at Harvard university campus 1', 
    'Vehicle backed into scaffold structure causing partial collapse. No injuries but equipment damage occurred.', 
    '2025-03-05T22:08:33.479Z', 
    'South entrance', 
    'Struck By', 
    'moderate', 
    'reported', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    7, 
    'Environmental incident at Harvard university campus 1', 
    'Chemical spill occurred in storage area. Approximately 2 gallons of paint thinner spilled. Area was contained and cleaned according to protocol.', 
    '2025-04-18T02:57:11.894Z', 
    'Electrical room', 
    'Environmental', 
    'critical', 
    'resolved', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by equipment failure',
    'Actions taken: Procedures updated',
    'To prevent recurrence: Daily equipment inspections',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    8, 
    'Fall incident at Harvard university campus 1', 
    'Worker slipped on wet floor where caution sign was not placed after mopping.', 
    '2025-02-26T21:25:02.300Z', 
    'North wing, 3rd floor', 
    'Fall', 
    'minor', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    14, 
    'Equipment Failure incident at Harvard university campus 1', 
    'Electrical short in temporary wiring caused small fire. Fire was extinguished with nearby extinguisher. No structural damage.', 
    '2025-04-14T14:41:34.903Z', 
    'North wing, 3rd floor', 
    'Equipment Failure', 
    'minor', 
    'resolved', 
    true, 
    'Worker received minor injury requiring first aid.',
    'Investigation determined that the incident was caused by equipment failure',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Improved signage installed',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    8, 
    'Slip/Trip incident at Harvard university campus 1', 
    'Heavy equipment operator reported near-miss with pedestrian worker who entered operational zone without authorization.', 
    '2025-03-22T12:23:35.581Z', 
    'West loading dock', 
    'Slip/Trip', 
    'minor', 
    'reported', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    6, 
    'Electrical incident at Harvard university campus 1', 
    'Excavation wall partially collapsed during heavy rain. No workers were in the trench at the time.', 
    '2025-03-18T16:44:59.756Z', 
    'Equipment yard', 
    'Electrical', 
    'moderate', 
    'resolved', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by environmental factors',
    'Actions taken: Environmental controls improved',
    'To prevent recurrence: Improved signage installed',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    14, 
    'Fall incident at Harvard university campus 1', 
    'Vehicle backed into scaffold structure causing partial collapse. No injuries but equipment damage occurred.', 
    '2025-04-29T07:41:40.140Z', 
    'South entrance', 
    'Fall', 
    'moderate', 
    'resolved', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by equipment failure',
    'Actions taken: Equipment replaced',
    'To prevent recurrence: Daily equipment inspections',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    7, 
    'Other incident at Harvard university campus 1', 
    'Heavy equipment operator reported near-miss with pedestrian worker who entered operational zone without authorization.', 
    '2025-02-23T08:48:28.459Z', 
    'East stairwell', 
    'Other', 
    'minor', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by environmental factors',
    'Actions taken: Environmental controls improved',
    'To prevent recurrence: Enhanced monitoring process',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    13, 
    'Other incident at Harvard university campus 1', 
    'Vehicle backed into scaffold structure causing partial collapse. No injuries but equipment damage occurred.', 
    '2025-05-11T21:51:56.055Z', 
    'Basement level', 
    'Other', 
    'major', 
    'investigating', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    8, 
    'Fall incident at Harvard university campus 1', 
    'Worker received minor cut on hand while using box cutter. First aid was administered on site.', 
    '2025-05-20T01:10:49.883Z', 
    'West loading dock', 
    'Fall', 
    'moderate', 
    'reported', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    7, 
    'Electrical incident at Harvard university campus 1', 
    'Water pipe burst causing flooding in basement level. Electrical equipment was exposed to water.', 
    '2025-04-05T12:33:03.908Z', 
    'South entrance', 
    'Electrical', 
    'moderate', 
    'reported', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    16, 
    'Equipment Failure incident at Harvard university campus 1', 
    'Excavation wall partially collapsed during heavy rain. No workers were in the trench at the time.', 
    '2025-02-25T20:40:53.799Z', 
    'Storage room B', 
    'Equipment Failure', 
    'moderate', 
    'investigating', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    13, 
    'Other incident at Harvard university campus 1', 
    'Water pipe burst causing flooding in basement level. Electrical equipment was exposed to water.', 
    '2025-03-10T22:09:45.527Z', 
    'Elevator shaft', 
    'Other', 
    'moderate', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    4, 
    'Fire/Explosion incident at Harvard university campus 1', 
    'Subcontractor was not wearing proper PPE while operating cutting tool.', 
    '2025-04-21T12:23:34.467Z', 
    'North wing, 3rd floor', 
    'Fire/Explosion', 
    'critical', 
    'investigating', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    13, 
    'Chemical Spill incident at Harvard university campus 1', 
    'Water pipe burst causing flooding in basement level. Electrical equipment was exposed to water.', 
    '2025-03-22T08:14:46.586Z', 
    'Main hallway', 
    'Chemical Spill', 
    'moderate', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    6, 
    'Fall incident at Harvard university campus 1', 
    'Water pipe burst causing flooding in basement level. Electrical equipment was exposed to water.', 
    '2025-04-26T08:14:54.170Z', 
    'Main hallway', 
    'Fall', 
    'critical', 
    'resolved', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by inadequate training',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Regular safety training scheduled',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    4, 
    'Electrical incident at Harvard university campus 1', 
    'Electrical short in temporary wiring caused small fire. Fire was extinguished with nearby extinguisher. No structural damage.', 
    '2025-03-30T00:06:25.985Z', 
    'Storage room B', 
    'Electrical', 
    'minor', 
    'investigating', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    14, 
    'Slip/Trip incident at Harvard university campus 1', 
    'Excavation wall partially collapsed during heavy rain. No workers were in the trench at the time.', 
    '2025-04-01T19:30:56.617Z', 
    'East stairwell', 
    'Slip/Trip', 
    'critical', 
    'resolved', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by inadequate training',
    'Actions taken: Equipment replaced',
    'To prevent recurrence: Improved signage installed',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    4, 
    'Caught In/Between incident at Harvard university campus 1', 
    'Worker slipped on wet floor where caution sign was not placed after mopping.', 
    '2025-04-25T09:58:38.965Z', 
    'Storage room B', 
    'Caught In/Between', 
    'critical', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by environmental factors',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Daily equipment inspections',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    14, 
    'Vehicle Accident incident at Harvard university campus 1', 
    'Vehicle backed into scaffold structure causing partial collapse. No injuries but equipment damage occurred.', 
    '2025-03-23T09:05:56.492Z', 
    'Scaffolding on north face', 
    'Vehicle Accident', 
    'major', 
    'resolved', 
    true, 
    'Worker received minor injury requiring first aid.',
    'Investigation determined that the incident was caused by inadequate training',
    'Actions taken: Environmental controls improved',
    'To prevent recurrence: Regular safety training scheduled',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    7, 
    'Equipment Failure incident at Harvard university campus 1', 
    'Water pipe burst causing flooding in basement level. Electrical equipment was exposed to water.', 
    '2025-03-31T13:36:56.173Z', 
    'Elevator shaft', 
    'Equipment Failure', 
    'minor', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by equipment failure',
    'Actions taken: Procedures updated',
    'To prevent recurrence: Daily equipment inspections',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    13, 
    'Environmental incident at Harvard university campus 1', 
    'Vehicle backed into scaffold structure causing partial collapse. No injuries but equipment damage occurred.', 
    '2025-03-08T00:40:04.397Z', 
    'North wing, 3rd floor', 
    'Environmental', 
    'moderate', 
    'closed', 
    false, 
    NULL,
    'Investigation determined that the incident was caused by inadequate training',
    'Actions taken: Additional training implemented',
    'To prevent recurrence: Enhanced monitoring process',
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    6, 
    'Caught In/Between incident at Harvard university campus 1', 
    'Excavation wall partially collapsed during heavy rain. No workers were in the trench at the time.', 
    '2025-05-22T01:39:16.270Z', 
    'Scaffolding on north face', 
    'Caught In/Between', 
    'minor', 
    'reported', 
    true, 
    'Worker received minor injury requiring first aid.',
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    6, 
    'Security incident at Harvard university campus 1', 
    'Chemical spill occurred in storage area. Approximately 2 gallons of paint thinner spilled. Area was contained and cleaned according to protocol.', 
    '2025-03-12T00:25:42.047Z', 
    'South entrance', 
    'Security', 
    'minor', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
INSERT INTO incident_reports (
    tenant_id, 
    site_id, 
    reported_by_id, 
    title, 
    description, 
    incident_date, 
    location, 
    incident_type, 
    severity, 
    status, 
    injury_occurred, 
    injury_details,
    root_cause,
    corrective_actions,
    preventative_measures,
    created_at, 
    updated_at, 
    is_active
  ) VALUES (
    1, 
    1, 
    13, 
    'Other incident at Harvard university campus 1', 
    'Electrical short in temporary wiring caused small fire. Fire was extinguished with nearby extinguisher. No structural damage.', 
    '2025-02-26T19:45:52.826Z', 
    'East stairwell', 
    'Other', 
    'minor', 
    'investigating', 
    false, 
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(), 
    NOW(), 
    true
  );
COMMIT;
